### ISSUE TITLE
Not working on WSL 2

### ISSUE THREAD

**Issue by davixcky** [mxschmitt/playwright-go#67]
Hi, 

I'm using playwright on this project [hippokampe](https://github.com/hippokampe) specifically in the [api module](https://github.com/hippokampe/api). This app is already tested in vagrant and linux pc, with positive results, but in the case of WSL 2, it's not working properly. 

I debugged the project, and I can conclude that the problem it's raised right [here](https://github.com/hippokampe/api/blob/dev/holberton/handlers.go#L17). I don't receive an error but blocks the execution, like an infinite loop. 

Thanks

**Comment by mxschmitt** [comment]
Would be great if you could set the environment variable `DEBUG` to `*` and provide me the output which gets send to the stderr then. Like e.g. `DEBUG=* go run main.go` thanks!

**Comment by davixcky** [comment]
Okay, this is the output. 
![image](https://user-images.githubusercontent.com/34346877/103160497-f9231780-47a3-11eb-905b-28b10dbf6457.png)
`

https://user-images.githubusercontent.com/34346877/103160509-2b347980-47a4-11eb-8422-ca1f55461cf2.mp4

`

**Comment by mxschmitt** [comment]
Hi, I unfortunately have no Windows environment yet, will create one, to give you feedback until tomorrow on that. Thats for reporting.

**Comment by mxschmitt** [comment]
Unfortunately WSL2 is not compatible with VirtualBox, so its hard for me to reproduce :/

Helpful things would be:
- Could you try the latest version (go get -u github.com/mxschmitt/playwright-go) - I changed quite a bit
- Could you try the minimal example like this one, to check if the issue is there also persistent: https://github.com/mxschmitt/playwright-go#example

Thanks and sorry for the inconvience!

**Comment by davixcky** [comment]
I'm gonna close the issue because I'm changing the logic on the app side so it will not require  installation over WSL, but once I make some version, I will test again to give you some feedback. Thanks for your help.
